import QRCode from 'qrcode';

export interface QRGenerateOptions {
  errorCorrectionLevel?: 'L' | 'M' | 'Q' | 'H';
  width?: number;
  margin?: number;
  color?: {
    dark?: string;
    light?: string;
  };
}

export async function generateQRPngDataUrl(
  content: string,
  options: QRGenerateOptions = {}
): Promise<string> {
  const opts = {
    errorCorrectionLevel: options.errorCorrectionLevel || 'M',
    width: options.width || 400,
    margin: options.margin !== undefined ? options.margin : 2,
    color: {
      dark: options.color?.dark || '#000000',
      light: options.color?.light || '#FFFFFF',
    },
  };
  return await QRCode.toDataURL(content, opts);
}

export async function generateQRSvgString(
  content: string,
  options: QRGenerateOptions = {}
): Promise<string> {
  const opts = {
    errorCorrectionLevel: options.errorCorrectionLevel || 'M',
    width: options.width || 400,
    margin: options.margin !== undefined ? options.margin : 2,
    color: {
      dark: options.color?.dark || '#000000',
      light: options.color?.light || '#FFFFFF',
    },
  };
  return await QRCode.toString(content, { ...opts, type: 'svg' });
}

export function downloadFile(dataUrlOrString: string, filename: string, isSvg: boolean = false) {
  const link = document.createElement('a');
  if (isSvg) {
    const blob = new Blob([dataUrlOrString], { type: 'image/svg+xml;charset=utf-8' });
    link.href = URL.createObjectURL(blob);
  } else {
    link.href = dataUrlOrString;
  }
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.opacity = '0';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch {
    return false;
  }
}

export async function shareContent(title: string, text: string, url?: string): Promise<boolean> {
  try {
    if (navigator.share) {
      await navigator.share({
        title,
        text,
        url: url || undefined,
      });
      return true;
    }
    return false;
  } catch (e) {
    console.warn('Share API cancelled or unsupported:', e);
    return false;
  }
}

export function printImageElement(imgSrc: string, title: string = 'QR Code Printout') {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: sans-serif;
            text-align: center;
            padding: 40px;
            margin: 0;
            background: #ffffff;
            color: #000000;
          }
          .card {
            display: inline-block;
            border: 2px solid #333;
            border-radius: 12px;
            padding: 24px;
            margin-top: 20px;
          }
          img {
            max-width: 320px;
            height: auto;
          }
          h2 {
            margin: 12px 0 4px;
            font-size: 20px;
          }
          p {
            font-size: 14px;
            color: #555;
            word-break: break-all;
            max-width: 360px;
            margin: 8px auto 0;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <img src="${imgSrc}" alt="QR Code" />
          <h2>${title}</h2>
          <p>Generated by Vesta Dairy OS Supply Chain Portal</p>
        </div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          }
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export function detectQRContentType(text: string): 'url' | 'email' | 'phone' | 'wifi' | 'geo' | 'json' | 'text' {
  const trimmed = text.trim();
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) return 'url';
  if (trimmed.startsWith('mailto:')) return 'email';
  if (trimmed.startsWith('tel:') || trimmed.startsWith('sms:')) return 'phone';
  if (trimmed.startsWith('WIFI:')) return 'wifi';
  if (trimmed.startsWith('geo:')) return 'geo';
  if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {
    try {
      JSON.parse(trimmed);
      return 'json';
    } catch {
      // fallthrough to text
    }
  }
  return 'text';
}
